[plotly-artifacts]
git-tree-sha1 = "f71c61fa03405ec1280c56d53d410b13ef9f228f"

    [[plotly-artifacts.download]]
    sha256 = "99ca59a00a8c00d7bbbe30a5ade812d23ff91709178df011c95ce461b7307f5f"
    url = "https://github.com/jonas-kr/PlotlyJS.jl/releases/download/plotly-artifacts-2.1.0/plotly-artifacts-2.1.0.tar.gz"
